---
services:
  server:
    image: docker.gitea.com/gitea:${GITEA_IMAGE:-latest}
    restart: always
    container_name: ${GITEA_NAME:-gitea-app}
    env_file:
      - .env
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=${GITEA_DB_TYPE}
      - GITEA__database__HOST=db:${MYSQL_PORT}
      - GITEA__database__NAME=${MYSQL_DB}
      - GITEA__database__USER=${MYSQL_USER}
      - GITEA__database__PASSWD=${MYSQL_PASS}
    volumes:
      - ${GITEA_VOLUME}/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${GITEA_PORT}:3000
      - ${GITEA_PORT_SSH}:22
    networks:
      - gitea
    depends_on:
      - db               

  db:
    image: docker.io/library/mysql:9.4.0
    restart: always
    container_name: gitea-db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASS}
      - MYSQL_DATABASE=${MYSQL_DB}
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - gitea
    volumes:
      - ${GITEA_VOLUME}/mysql:/var/lib/mysql

volumes:
  gitea-data:
    name: ${GITEA_VOLUME}

networks:
  gitea:
    name: gitea-net
    driver: bridge
